version: '3.8'

services:
  frontend:
    container_name: kanva-ops_frontend
    build:
      context: ./kanvaOps.front
      dockerfile: Dockerfile
    # depends_on:
    #   - backend
    ports:
      - "6969:80"

  # backend:
  #   container_name: kanva-ops_backend
  #   build:
  #     context: ./kanvaOps.backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"  
  #   environment:
  #     - MONGO_URI=mongodb://mongo:27017/kanvaopsdb
  #   depends_on:
  #     - mongo

  mongo:
    container_name: kanva-ops_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: